### ISSUE TITLE
Issues with installing the "rethinking" package in RStudio

### ISSUE THREAD

**Issue by Winnie0057** [rmcelreath/stat_rethinking_2023#12]
A colleague and I are going through the 'Statistical Rethinking' series, but we are unable to install the "rethinking" package in RStudio. This is the warning message in R,  "package ‘rethinking’ is not available for this version of R". 

We are unsure why this is happening because we are using the latest version of R. We would appreciate your suggestions on how to go about the issue. 

Thanks!

**Comment by rmcelreath** [comment]
The package is not on CRAN. It must be installed from github: https://github.com/rmcelreath/rethinking#installation
